In [ ]:
# part-1
# question 1

In [ ]:
# tensor
# constant
# variable


In [ ]:
# question 2

In [ ]:
# In TensorFlow the differences between constants and variables are that when you declare some constant, its value can't be changed in the future (also the initialization should be with a value, not with operation). Nevertheless, when you declare a Variable, you can change its value in the future with tf.

In [ ]:
import tensorflow as tf

# Create a TensorFlow variable
weights = tf.Variable([0.5, 0.3, 0.1])

In [ ]:
# Modify the value of the TensorFlow variable
weights.assign([0.6, 0.2, 0.2])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([0.6, 0.2, 0.2], dtype=float32)>

In [ ]:
weights

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0.6, 0.2, 0.2], dtype=float32)>

In [ ]:
# Create a TensorFlow constant
input_data = tf.constant([1, 2, 3, 4])

In [ ]:
# question 3

In [ ]:
# Tensorflow provides a built-in function called matmul that can perform matrix multiplication efficiently. The matmul function takes two tensors as input and produces a new tensor as output.
# Element-wise multiplication is a mathematical operation that performs multiplication between two matrices or tensors of the same shape. The result of element-wise multiplication is a new tensor that has the same shape as the input tensors.
# create two matrices and using "add" to adding the numbers in two matrices

In [ ]:
# part-2
# task-1

In [ ]:
A=tf.random.normal(shape=[3,3])
B=tf.random.truncated_normal(shape=[4,4])
C=tf.random.normal(shape=[2,2],mean=3,stddev=0.5)

In [ ]:
A

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.4397306 , -0.8557966 , -0.39338335],
       [ 0.5568725 ,  0.9339817 , -0.92963356],
       [-1.0485016 ,  1.1716241 ,  0.23886728]], dtype=float32)>

In [ ]:
B

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.7890122 ,  0.09325914,  0.27984384,  0.34708264],
       [ 1.118126  ,  0.48629284,  0.31808364, -0.77479225],
       [ 0.13575889, -0.15252058,  0.26987866, -1.5522298 ],
       [-1.5707049 ,  0.6496324 , -0.32281318,  0.5336022 ]],
      dtype=float32)>

In [ ]:
C

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.8200722, 3.3819644],
       [3.0670257, 3.0844777]], dtype=float32)>

In [ ]:
B_cropped= B[:3,:3]

In [ ]:
B_cropped

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.4042019 , -1.2471364 ,  0.56127614],
       [ 0.24226283, -0.8788146 , -0.55173725],
       [ 1.5314165 ,  0.30959088, -0.46621963]], dtype=float32)>

In [ ]:
D=tf.add(A,B_cropped)

In [ ]:
D_cropped=D[:2,:2]

In [ ]:
E=tf.matmul(C,D_cropped)

In [ ]:
E

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.581696 , -4.3225374],
       [ 3.789213 , -3.987059 ]], dtype=float32)>

In [ ]:
# task-2

In [ ]:
F=tf.random.uniform(shape=[3,3])
F

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.23592281, 0.626336  , 0.40903938],
       [0.7310152 , 0.34490645, 0.87205434],
       [0.01911187, 0.38276052, 0.14876163]], dtype=float32)>

In [ ]:
G=tf.transpose(F)
G

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.23592281, 0.7310152 , 0.01911187],
       [0.626336  , 0.34490645, 0.38276052],
       [0.40903938, 0.87205434, 0.14876163]], dtype=float32)>

In [ ]:
H=tf.exp(F)
H

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.2660766, 1.8707435, 1.505371 ],
       [2.0771883, 1.4118578, 2.3918195],
       [1.0192957, 1.4663268, 1.1603963]], dtype=float32)>

In [ ]:
I=tf.concat(values=(F,G),axis=0)
J=tf.concat(values=(F,G),axis=1)



In [ ]:
I

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[0.23592281, 0.626336  , 0.40903938],
       [0.7310152 , 0.34490645, 0.87205434],
       [0.01911187, 0.38276052, 0.14876163],
       [0.23592281, 0.7310152 , 0.01911187],
       [0.626336  , 0.34490645, 0.38276052],
       [0.40903938, 0.87205434, 0.14876163]], dtype=float32)>

In [ ]:
J

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0.23592281, 0.626336  , 0.40903938, 0.23592281, 0.7310152 ,
        0.01911187],
       [0.7310152 , 0.34490645, 0.87205434, 0.626336  , 0.34490645,
        0.38276052],
       [0.01911187, 0.38276052, 0.14876163, 0.40903938, 0.87205434,
        0.14876163]], dtype=float32)>