In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


In [4]:
X,y=load_iris(return_X_y=True)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [7]:
from sklearn.naive_bayes import GaussianNB


In [8]:
gnb=GaussianNB()

In [11]:
gnb.fit(X_train,y_train)

GaussianNB()

In [12]:
y_pred=gnb.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [15]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [24]:
import seaborn as sns
ds=sns.load_dataset('tips')

In [26]:
ds.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
import pandas as pd
import numpy as np


In [27]:
df=ds[['total_bill','tip']]

In [29]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [94]:
encoder=lbl_encoder.fit_transform(ds[['time']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [98]:
encoder=pd.DataFrame(encoder)

In [100]:
lbl_encoder.transform([['Dinner']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0])

In [101]:
lbl_encoder.transform([['Lunch']])

array([1])

In [102]:
dff=pd.concat([df,encoder],axis=1)

In [103]:
dff.head()

total_bill   tip  0
0       16.99  1.01  0
1       10.34  1.66  0
2       21.01  3.50  0
3       23.68  3.31  0
4       24.59  3.61  0

In [104]:
dff['target']=dff[0]

In [105]:
dff.head()

total_bill   tip  0  target
0       16.99  1.01  0       0
1       10.34  1.66  0       0
2       21.01  3.50  0       0
3       23.68  3.31  0       0
4       24.59  3.61  0       0

In [107]:
X=dff.iloc[:,:2]
y=dff.iloc[:,-1]

In [108]:
X

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [109]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    0
241    0
242    0
243    0
Name: target, Length: 244, dtype: int64

In [110]:
from sklearn.model_selection import train_test_split

In [111]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [112]:
from sklearn.naive_bayes import GaussianNB

In [113]:
gnb=GaussianNB()

In [114]:
gnb.fit(X_train,y_train)

GaussianNB()

In [115]:
y_pred=gnb.predict(X_test)

In [116]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [117]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[56 18]
 [ 0  0]]
0.7567567567567568
              precision    recall  f1-score   support

           0       1.00      0.76      0.86        74
           1       0.00      0.00      0.00         0

    accuracy                           0.76        74
   macro avg       0.50      0.38      0.43        74
weighted avg       1.00      0.76      0.86        74



/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
