In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [ ]:
# question 1

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [7]:
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

In [ ]:
# question 2

In [19]:
array_list.dtype

dtype('<U1')

In [ ]:
# question3

In [23]:
array_list = np.array(object = list_, dtype = int)


In [27]:
array_list.dtype

dtype('int64')

In [ ]:
# question 4

In [30]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [31]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
num_array.size

6

In [33]:
num_array.shape

(2, 3)

In [34]:
arr=np.zeros((3,3))

In [35]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# question 6

In [36]:
arr1=np.eye(5,5)

In [37]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])