In [1]:
import numpy as np


In [2]:
l=[1,2,3,45]

In [4]:
arr=np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [11]:
np.asarray(l)

array([ 1,  2,  3, 45])

In [10]:
arr1=np.array([[1,2,3],[4,5,6]])

In [13]:
arr.ndim

1

In [14]:
arr1.ndim

2

In [16]:
jack=np.matrix(l)

In [17]:
np.asanyarray(l)

array([ 1,  2,  3, 45])

In [18]:
np.asanyarray(jack)

matrix([[ 1,  2,  3, 45]])

In [19]:
a=arr

In [20]:
a

array([ 1,  2,  3, 45])

In [21]:
arr[0]=9499

In [22]:
arr

array([9499,    2,    3,   45])

In [23]:
a

array([9499,    2,    3,   45])

In [24]:
b=np.copy(arr)

In [25]:
b

array([9499,    2,    3,   45])

In [26]:
b[3]=44

In [27]:
b

array([9499,    2,    3,   44])

In [28]:
arr

array([9499,    2,    3,   45])

In [30]:
np.fromfunction(lambda i,j : i!=j ,(4,4))

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [34]:
iterable=list( i+i for i in range(4))

In [36]:
np.fromiter(iterable,int)

array([0, 2, 4, 6])

In [38]:
np.fromstring('34 4  34 34',sep=' ')

array([34.,  4., 34., 34.])

In [41]:
np.fromstring('344,34,34',sep=',')

array([344.,  34.,  34.])

In [43]:
arr.size

4

In [44]:
arr1.size

6

In [45]:
arr

array([9499,    2,    3,   45])

In [46]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr.shape

(4,)

In [48]:
arr1.shape

(2, 3)

In [49]:
arr.dtype

dtype('int64')

In [50]:
arr1.dtype

dtype('int64')

In [54]:
np.arange(0.5,10,2)


array([0.5, 2.5, 4.5, 6.5, 8.5])

In [56]:
np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [62]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [2]:
import numpy as np
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
np.zeros((2,3,6,7))

array([[[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0

In [6]:
np.random.rand(3,5)

array([[0.71026721, 0.4192295 , 0.5119571 , 0.98018935, 0.30277682],
       [0.9193578 , 0.73226842, 0.93695194, 0.53776425, 0.83189779],
       [0.41991102, 0.7527612 , 0.75539878, 0.45837566, 0.42363072]])

In [7]:
np.random.randn(3,5)

array([[ 0.98853718,  0.78624811, -0.45621802, -0.20031887, -3.14533445],
       [ 0.62915083, -0.16817467,  0.32348265, -0.50606633, -0.04982863],
       [-0.38859061, -1.48555963, -0.02818421,  0.35900842,  0.6259703 ]])

In [9]:
arr2=np.random.randint(1,5,(4,3))

In [10]:
arr2.size

12

In [11]:
arr2.shape

(4, 3)

In [13]:
arr2.reshape(2,6)

array([[1, 3, 1, 4, 1, 2],
       [1, 4, 4, 1, 1, 4]])

In [15]:
arr2.reshape(3,-19779798)

array([[1, 3, 1, 4],
       [1, 2, 1, 4],
       [4, 1, 1, 4]])

In [24]:
arr2=np.random.randint(3,7,(4,8))

In [25]:
arr2

array([[3, 6, 4, 4, 6, 3, 4, 4],
       [4, 5, 6, 3, 5, 5, 3, 3],
       [6, 5, 5, 6, 5, 6, 4, 4],
       [4, 4, 5, 5, 5, 3, 6, 4]])

In [28]:
arr2[3,[0,1]]

array([4, 4])

In [29]:
arr2[2:4,[6,7]]

array([[4, 4],
       [6, 4]])

In [31]:
arr1=np.random.randint(1,3,(2,2))

In [32]:
arr2=np.random.randint(1,3,(2,2))

In [33]:
arr1+arr2

array([[3, 4],
       [2, 3]])

In [34]:
arr1

array([[2, 2],
       [1, 1]])

In [35]:
arr2

array([[1, 2],
       [1, 2]])

In [36]:
arr2-arr1

array([[-1,  0],
       [ 0,  1]])

In [37]:
arr2/arr1

array([[0.5, 1. ],
       [1. , 2. ]])

In [38]:
arr1@arr2

array([[4, 8],
       [2, 4]])

In [39]:
arr1

array([[2, 2],
       [1, 1]])

In [40]:
arr2

array([[1, 2],
       [1, 2]])

In [42]:
arr=np.random.randint(2,8,(2,2))

In [43]:
arr

array([[4, 4],
       [2, 6]])

In [47]:
a=np.array([1,2])

In [48]:
a

array([1, 2])

In [49]:
arr+a

array([[5, 6],
       [3, 8]])

In [54]:
b=np.array([[3,4]])

In [56]:
b=b.T

In [57]:
b

array([[3],
       [4]])

In [58]:
arr+b

array([[ 7,  7],
       [ 6, 10]])

In [59]:
arr

array([[4, 4],
       [2, 6]])

In [60]:
np.sqrt(arr)

array([[2.        , 2.        ],
       [1.41421356, 2.44948974]])

In [61]:
np.log10(arr)

array([[0.60205999, 0.60205999],
       [0.30103   , 0.77815125]])

In [62]:
np.exp(arr)

array([[ 54.59815003,  54.59815003],
       [  7.3890561 , 403.42879349]])

In [63]:
np.min(arr)

2

In [64]:
np.max(arr)

6

In [68]:
arr=np.random.randint(2,9,(4,5))

In [66]:
arr

array([[5, 7, 5, 7, 3],
       [5, 4, 8, 3, 4],
       [5, 8, 6, 3, 2],
       [3, 7, 2, 6, 8],
       [3, 4, 6, 7, 2]])

In [69]:
arr.transpose()

array([[3, 3, 7, 4],
       [4, 2, 6, 7],
       [7, 7, 6, 6],
       [7, 2, 5, 3],
       [2, 7, 7, 7]])

In [71]:
arr.reshape(2,10)

array([[3, 4, 7, 7, 2, 3, 2, 7, 2, 7],
       [7, 6, 6, 5, 7, 4, 7, 6, 3, 7]])

In [73]:
np.expand_dims(arr,axis=0)

array([[[3, 4, 7, 7, 2],
        [3, 2, 7, 2, 7],
        [7, 6, 6, 5, 7],
        [4, 7, 6, 3, 7]]])

In [74]:
np.expand_dims(arr,axis=1)

array([[[3, 4, 7, 7, 2]],

       [[3, 2, 7, 2, 7]],

       [[7, 6, 6, 5, 7]],

       [[4, 7, 6, 3, 7]]])

In [76]:
arr.flatten()

array([3, 4, 7, 7, 2, 3, 2, 7, 2, 7, 7, 6, 6, 5, 7, 4, 7, 6, 3, 7])

In [77]:
d=np.array([[1],[2],[3]])

In [79]:
np.squeeze(d)

array([1, 2, 3])

In [80]:
d.flatten()

array([1, 2, 3])

In [83]:
np.repeat(d,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [89]:
np.roll(d,3
       )

array([[1],
       [2],
       [3]])

In [91]:
np.diag(np.array([1,2,3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [3]:
arr1=np.random.randint(2,9,(3,3))

In [4]:
arr2=np.random.randint(2,9,(3,3))

In [5]:
arr1

array([[2, 3, 7],
       [3, 8, 7],
       [2, 8, 4]])

In [97]:
arr2

array([[4, 7, 5],
       [8, 4, 5],
       [7, 2, 6]])

In [98]:
arr1**arr2

array([[   625,  16384,  32768],
       [   256,    256,     32],
       [  2187,     36, 262144]])

In [99]:
~arr1

array([[-6, -5, -9],
       [-3, -5, -3],
       [-4, -7, -9]])

In [100]:
arr=np.array(['jack','kallis'])

In [101]:
arr

array(['jack', 'kallis'], dtype='<U6')

In [103]:
np.char.upper(arr)

array(['JACK', 'KALLIS'], dtype='<U6')

In [104]:
np.char.capitalize(arr)

array(['Jack', 'Kallis'], dtype='<U6')

In [105]:
np.char.title(arr)

array(['Jack', 'Kallis'], dtype='<U6')

In [106]:
arr1


array([[5, 4, 8],
       [2, 4, 2],
       [3, 6, 8]])

In [107]:
np.sin(arr1)

array([[-0.95892427, -0.7568025 ,  0.98935825],
       [ 0.90929743, -0.7568025 ,  0.90929743],
       [ 0.14112001, -0.2794155 ,  0.98935825]])

In [108]:
np.cos(arr1)

array([[ 0.28366219, -0.65364362, -0.14550003],
       [-0.41614684, -0.65364362, -0.41614684],
       [-0.9899925 ,  0.96017029, -0.14550003]])

In [109]:
np.tan(arr1)

array([[-3.38051501,  1.15782128, -6.79971146],
       [-2.18503986,  1.15782128, -2.18503986],
       [-0.14254654, -0.29100619, -6.79971146]])

In [110]:
np.mean(arr1)

4.666666666666667

In [112]:
np.median(arr1)

4.0

In [113]:
arr1

array([[5, 4, 8],
       [2, 4, 2],
       [3, 6, 8]])

In [6]:
import numpy as np
np.var(arr1)

5.876543209876543

In [8]:
np.subtract(arr2,arr1)

array([[ 2,  0, -1],
       [ 5, -4, -4],
       [ 0, -1,  3]])

In [2]:
arr1

NameError: name 'arr1' is not defined

In [10]:
arr2

array([[4, 3, 6],
       [8, 4, 3],
       [2, 7, 7]])

In [11]:
np.multiply(arr1,arr2)

array([[ 8,  9, 42],
       [24, 32, 21],
       [ 4, 56, 28]])

In [12]:
np.power(arr1,2)

array([[ 4,  9, 49],
       [ 9, 64, 49],
       [ 4, 64, 16]])

In [13]:
np.mod(arr1,arr2)

array([[2, 0, 1],
       [3, 0, 1],
       [0, 1, 4]])

In [1]:
import numpy as np

In [5]:
arr1

array([[3, 6, 4],
       [5, 2, 6],
       [2, 8, 2]])

In [6]:
arr2

array([[2, 2, 6],
       [2, 7, 8],
       [7, 4, 4]])

In [18]:
arr=np.sort([4,2,545,0,2,4,0,9898,0])

In [8]:
arr

array([   2,    4,   24,  545, 9898])

In [11]:
arr.sort()

In [12]:
arr

array([   2,    4,   24,  545, 9898])

In [17]:
np.searchsorted(arr,5)

2

In [20]:
np.count_nonzero(arr)

6

In [21]:
np.where(arr>100)

(array([7, 8]),)

In [26]:
arr

array([   0,    0,    0,    2,    2,    4,    4,  545, 9898])

In [27]:
np.extract(arr>20,arr)

array([ 545, 9898])

In [29]:
arr

array([   0,    0,    0,    2,    2,    4,    4,  545, 9898])

In [31]:
arr.byteswap()

array([                   0,                    0,                    0,
         144115188075855872,   144115188075855872,   288230376151711744,
         288230376151711744,  2378463553205043200, -6186257038146797568])

In [32]:
b=arr.view()

In [33]:
b

array([   0,    0,    0,    2,    2,    4,    4,  545, 9898])

In [34]:
b[0]=34

In [35]:
b

array([  34,    0,    0,    2,    2,    4,    4,  545, 9898])

In [36]:
arr

array([  34,    0,    0,    2,    2,    4,    4,  545, 9898])

In [37]:
import numpy.matlib as nm

In [38]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [39]:
nm.ones((3,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [40]:
nm.eye(4,4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [41]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
arr1=np.random.randint([[2,3],[3,4]])

In [47]:
arr1

array([[0, 2],
       [1, 2]])

In [48]:
arr2=np.random.randint([[2,3],[3,4]])

In [49]:
arr2

array([[1, 2],
       [2, 0]])

In [ ]:
np.dot(arr1,arr2